name: Release Source Code

on:
  push:
    tags:
      - '*'
  
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of Valkey to release
        required: true

jobs:
    get-tag:
        name: Get metadata to build
        runs-on: ubuntu-latest
        outputs:
          TAG: ${{ steps.get_tag.outputs.TAG }}
        steps:
    
          - run: |
              echo "TAG: ${{ inputs.tag || github.ref_name }}"
            shell: bash
    
          # This step is to consolidate the three different triggers into a single "TAG"
          # 1. If manual dispatch - use the tag provided.
          # 3. If tag trigger, use that tag.
          - name: Get the Tag
            id: get_tag
            run: |
                TAG="${INPUT_TAG}"
                if [ -z "${TAG}" ]; then
                    false
                fi
                echo "TAG=$TAG" >> $GITHUB_OUTPUT
            shell: bash
            env:
              # Use the dispatch variable in preference, if empty use the context ref_name which should
              # only ever be a tag
              INPUT_TAG: ${{ inputs.tag || github.ref_name }}


    create-source-code-tarball:
        runs-on: 'ubuntu-latest'
        needs: get-tag
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: ${{ needs.get-tag.outputs.TAG }}
            
            - name: Create Tarball and sha256
              run: |
                TAG=${{needs.get-tag.outputs.TAG}}
                TARNAME="valkey-${TAG}.tar"
                echo "Generating /tmp/${TARNAME}"
                git archive $TAG --prefix valkey-${TAG}/ > /tmp/$TARNAME || exit 1
                echo "Gizipping the archive"
                rm -f /tmp/$TARNAME.gz
                gzip -9 /tmp/$TARNAME
                sha256sum /tmp/$TARNAME.gz > /tmp/$TARNAME.gz.sha256
                SHA=$(/tmp/$TARNAME.gz | shasum -a 256 | cut -f 1 -d' ')
                echo "ENTRY="hash ${TARNAME}.gz sha256 $SHA https://github.com/valkey-io/valkey/archive/refs/tags/${TAG}.tar.gz"" >> $GITHUB_ENV
                mkdir -p packages-files
                cp -rfv /tmp/$TARNAME* packages-files/
                cp -rfv packages-files/$TARNAME.gz packages-files/valkey_stable.tar.gz 
                sha256sum packages-files/valkey_stable.tar.gz > packages-files/valkey_stable.tar.gz.sha256
            
            - name: Configure AWS credentials
              run: |
                aws configure set region us-east-1
                aws configure set aws_access_key_id ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_S3_ACCESS_KEY }}
            
            - name: Sync to S3
              run: aws s3 sync packages-files s3://${{secrets.AWS_S3_BUCKET}}/releases/  
            
            - name: Trigger Release hash Workflow on `valkey-hashes`
              run: |
                curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.WORKFLOW_PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/roshkhatri/valkey-hashes/dispatches \
                -d '{"event_type": "release_hash", "client_payload": { "tag": "$ENTRY" }}'